import one from './image/icon/1.svg';
import two from './image/icon/2.svg';
import three from './image/icon/3.svg';
import four from './image/icon/4.svg';
import five from './image/icon/5.svg';
import six from './image/icon/6.svg';
import seven from './image/icon/7.svg';

const sectorsData = [
{
  id: 'bigSector0',
  value: 100,
  name: 'Квантовые технологии',
  company: 'Квантовые технологии',
  radius: 420,
  startAngle: 0,
  endAngle: 0.7,
  outerGradientId: '1',
  outerStartColor: 'E0CFFB',
  outerEndColor: 'CBE6F7',
  innerGradientId: '1',
  innerStartColor: '00a8f3',
  innerEndColor: '4d0fa5',
  img: one,
  outer: [{
    id: '0-1',
    name: 'Квантовые технологии',
    value: 100,
    radius: 420,
    startAngle: 0,
    endAngle: 0.7,
  }],
  inner: [{
    value: 100,
    startAngle: 0,
    endAngle: 0.7,
  }],
  childrens: [{
    id: '0-0',
    value: 100,
    name: 'Квантовые вычисления',
    radius: 380,
    startAngle: 0.0,
    endAngle: 0.3,
    innerGradientId: '1',
    startColor: 'CBE6F7',
    endColor: 'CBE6F7',
  }, {
    id: '0-1',
    value: 100,
    name: 'Квантовые коммуникации',
    radius: 300,
    innerRadius: 100,
    startAngle: 0.3,
    endAngle: 0.5,
    innerGradientId: '1',
    startColor: '3597e0',
    endColor: '5276e6',
  }, {
    id: '0-2',
    value: 100,
    name: 'Квантовые сенсоры и метрология',
    radius: 310,
    innerRadius: 100,
    startAngle: 0.5,
    endAngle: 0.7,
    innerGradientId: '1',
    startColor: 'ff0000',
    endColor: '00ffc8',
  }],
},
 {
  id: 'bigSector1',
  value: 200,
  name: 'Технологии беспроводной связи',
  company: 'Технологии беспроводной связи',
  radius: 470,
  startAngle: 0.7,
  endAngle: 1.6,
  outerGradientId: '2',
  outerStartColor: 'F1E8E1',
  outerEndColor: 'DDC3E8',
  innerGradientId: '2',
  innerStartColor: '8926A1',
  innerEndColor: 'D1AF8A',
  img: two,
  outer: [{
    id: '1-1',
    name: 'Технологии беспроводной связи',
    value: 200,
    radius: 450,
    startAngle: 0.7,
    endAngle: 1.6,
  }],
  inner: [{
    value: 200,
    startAngle: 0.7,
    endAngle: 1.6,
  }],
  childrens: [{
    id: '1-1',
    value: 200,
    name: 'WAN (LTE, 5G)',
    radius: 420,
    startAngle: 0.7,
    endAngle: 0.9,
  }, {
    id: '1-2',
    value: 200,
    name: 'LPWAN (NB-IoT, LTE-M, LoRaWan и другие)',
    radius: 350,
    startAngle: 0.9,
    endAngle: 1.1,
  }, {
    id: '1-3',
    value: 200,
    name: 'WLAN',
    radius: 320,
    startAngle: 1.1,
    endAngle: 1.3,
  }, {
    id: '1-4',
    value: 200,
    name: 'PAN (RFID, NFC и др.)',
    radius: 300,
    startAngle: 1.3,
    endAngle: 1.5,
  }, {
    id: '1-5',
    value: 200,
    name: 'Спутниковые технологии связи',
    radius: 310,
    startAngle: 1.5,
    endAngle: 1.6,
  }],
}, {
  id: 'bigSector2',
  value: 100,
  name: 'Компоненты робототехники и сенсорика',
  company: 'Компоненты робототехники и сенсорика',
  radius: 460,
  startAngle: 1.6,
  endAngle: 2.3,
  outerGradientId: '3',
  outerStartColor: 'CBE3C3',
  outerEndColor: 'EBEBD9',
  innerGradientId: '3',
  innerStartColor: 'D8B98A',
  innerEndColor: '469020',
  img: three,
  outer: [{
    id: '2-1',
    name: 'Компоненты робототехники и сенсорика',
    value: 100,
    radius: 440,
    startAngle: 1.6,
    endAngle: 2.3,
  }],
  inner: [{
    value: 200,
    startAngle: 1.6,
    endAngle: 2.3,
  }],
  childrens: [{
    id: '2-1',
    value: 100,
    name: 'Сенсоры и цифровые компоненты РТК для человеко-машинного взаимодействия',
    radius: 400,
    startAngle: 1.6,
    endAngle: 1.9,
  }, {
    id: '2-2',
    value: 100,
    name: 'Технологии сенсорно-моторной координации и пространственного позиционирования',
    radius: 390,
    startAngle: 1.9,
    endAngle: 2.1,
  }, {
    id: '2-3',
    value: 100,
    name: 'Сенсоры и обработка сенсорной информации',
    radius: 385,
    startAngle: 2.1,
    endAngle: 2.3,
  }],
}, {
  id: 'bigSector3',
  value: 100,
  name: 'Технологии виртуальной и дополненной реальности',
  company: 'Технологии виртуальной и дополненной реальности',
  radius: 400,
  startAngle: 2.3,
  endAngle: 2.9,
  outerGradientId: '4',
  outerStartColor: 'EEE1BE',
  outerEndColor: 'C4E0C7',
  innerGradientId: '4',
  innerStartColor: '528E1A',
  innerEndColor: 'EC9C09',
  img: four,
  outer: [{
    id: '3-1',
    name: 'Технологии виртуальной и дополненной реальности',
    value: 100,
    radius: 400,
    startAngle: 2.3,
    endAngle: 3.5,
  }],
  inner: [{
    value: 200,
    startAngle: 2.3,
    endAngle: 3.5,
  }],
  childrens: [{
    id: '3-1',
    value: 100,
    name: 'Средства разработки VR/AR-контента и технологии совершенствования пользовательского опыта (UX) со стороны разработчика',
    radius: 350,
    startAngle: 2.3,
    endAngle: 2.5,
  }, {
    id: '3-2',
    value: 100,
    name: 'Платформенные решения для пользователей: редакторы создания контента и его дистрибуции',
    radius: 340,
    startAngle: 2.5,
    endAngle: 2.7,
  }, {
    id: '3-3',
    value: 100,
    name: 'Технология захвата движения в VR/AR и фотограмметрии',
    radius: 380,
    startAngle: 2.7,
    endAngle: 2.9,
  }, {
    id: '3-4',
    value: 100,
    name: 'Интерфейсы обратной связи и сенсоры для VR/AR',
    radius: 340,
    startAngle: 2.9,
    endAngle: 3.1,
  }, {
    id: '3-5',
    value: 100,
    name: 'Технологии графического вывода',
    radius: 380,
    startAngle: 3.1,
    endAngle: 3.2,
  }, {
    id: '3-6',
    value: 100,
    name: 'Технологии оптимизации передачи данных для VR/AR',
    radius: 350,
    startAngle: 3.2,
    endAngle: 3.5,
  }],
}, {
  id: 'bigSector4',
  value: 100,
  name: 'Новые производственные технологии',
  company: 'Новые производственные технологии',
  radius: 480,
  startAngle: 3.5,
  endAngle: 4.5,
  outerGradientId: '5',
  outerStartColor: 'F4D3CE',
  outerEndColor: 'FADFCA',
  innerGradientId: '5',
  innerStartColor: 'F8A41E',
  innerEndColor: 'D95936',
  img: five,
  outer: [{
    id: '4-1',
    name: 'Новые производственные технологии',
    value: 100,
    radius: 450,
    startAngle: 3.5,
    endAngle: 4.5,
  }],
  inner: [{
    value: 200,
    startAngle: 3.5,
    endAngle: 4.5,
  }],
  childrens: [{
    id: '4-1',
    value: 100,
    name: 'Манипуляторы и технологии манипулирования',
    radius: 430,
    startAngle: 3.5,
    endAngle: 3.8,
  }, {
    id: '4-2',
    value: 100,
    name: 'Технологии "умного" производства (Smart manufacturing)',
    radius: 380,
    startAngle: 3.8,
    endAngle: 4.1,
  }, {
    id: '4-3',
    value: 100,
    name: 'Цифровое проектирование, математическое моделирование и управление жизненным циклом издели и продукции (Smart Design)',
    radius: 390,
    startAngle: 4.1,
    endAngle: 4.5,
  }]
}, {
  id: 'bigSector5',
  value: 100,
  name: 'Искусственный интеллект',
  company: 'Искусственный интеллект',
  radius: 470,
  startAngle: 4.5,
  endAngle: 5.6,
  outerGradientId: '6',
  outerStartColor: 'CBE3F5',
  outerEndColor: 'F6C9CC',
  innerGradientId: '6',
  innerStartColor: 'D5303F',
  innerEndColor: '368FD1',
  img: six,
  outer: [{
    id: '5-1',
    name: 'Искусственный интеллект',
    value: 100,
    radius: 470,
    startAngle: 4.5,
    endAngle: 5.6,
  }],
  inner: [{
    value: 200,
    startAngle: 4.5,
    endAngle: 5.6,
  }],
  childrens: [{
    id: '5-1',
    value: 100,
    name: 'Перспективные методы и технологии в ИИ',
    radius: 430,
    startAngle: 4.5,
    endAngle: 4.7,
  }, {
    id: '5-2',
    value: 100,
    name: 'Распознование и синтез речи',
    radius: 420,
    startAngle: 4.7,
    endAngle: 4.9,
  }, {
    id: '5-3',
    value: 100,
    name: 'Рекомендательные системы и интеллектуальные системы поддержки принятия решения',
    radius: 450,
    startAngle: 4.9,
    endAngle: 5.1,
  }, {
    id: '5-4',
    value: 100,
    name: 'Обработка естественного языка',
    radius: 420,
    startAngle: 5.1,
    endAngle: 5.3,
  }, {
    id: '5-5',
    value: 100,
    name: 'Компьютерное зрение',
    radius: 430,
    startAngle: 5.3,
    endAngle: 5.6,
  }]
}, {
  id: 'bigSector6',
  value: 100,
  name: 'Системы распределенного реестра',
  company: 'Системы распределенного реестра',
  radius: 450,
  startAngle: 5.6,
  endAngle: 6.3,
  outerGradientId: '7',
  outerStartColor: 'DAEAF7',
  outerEndColor: 'CEDAEA',
  innerGradientId: '7',
  innerStartColor: 'CEDAEA',
  innerEndColor: '6AA9DF',
  img: seven,
  outer: [{
    id: '6-1',
    name: 'Системы распределенного реестра',
    value: 100,
    radius: 450,
    startAngle: 5.6,
    endAngle: 6.29,
  }],
  inner: [{
    value: 200,
    startAngle: 5.6,
    endAngle: 6.29,
  }],
  childrens: [{
    id: '6-1',
    value: 100,
    name: 'Технологии создания и исполнения децентрализованных приложений и смарт-контрактов',
    radius: 415,
    startAngle: 5.6,
    endAngle: 5.8,
  }, {
    id: '6-2',
    value: 100,
    name: 'Технологии обеспечения целостности и непротиворечивости данных (консенсус)',
    radius: 400,
    startAngle: 5.8,
    endAngle: 6.0,
  }, {
    id: '6-3',
    value: 100,
    name: 'Технологии организации и синхронизации данных',
    radius: 430,
    startAngle: 6.0,
    endAngle: 6.29,
  }]
}];

export default sectorsData;
